# Conclusion

After reviewing the data, and taking a closer look at the driving forces behind box office dynamics, it's clear that the movie industry is driven by more than just ratings, and even genre. That being said, by investigating the data at our disposal, we were able to paint a clearer picture of the industry and see some of the nuances behind the blockbusters we hear so much about in headlines. In short - ratings matter less than executives think, and action / adventure blockbusters make a lot of money. 

At the end of the day, the entertainment industry is just like any other business. Studios have bottom lines, there are a number of factors that lead to a given film's success, and executives are often times trying to make a profit. As we've seen in recent headlines, the industry is also becoming much more consolidated. 

With that in mind, it's no surprise we saw what we did in the data. Despite criticism from industry insiders that ratings websites like Rotten Tomatoes or IMDB are pushing audiences away from the theater, we discovered that there is in fact little to no correlation with a movie's success at the box office and how it fares in theaters. Given the lower correlation rates, and the high degree of variability, we feel that we have enough evidence to object to many executive's claims that ratings aggregation websites are pushing viewers away from their films. We also see that as studios have consolidated (think Marvel and Star Wars going to Disney), studios are betting big on the titles and genres that typically do well. If we look at the last decade, and the top 10 box office successes, they have all been either 1) part of a franchise, 2) a sequel, or 3) a remake from a previous series. For some people, Marvel movies are the peak of cinema. For others, notably Martin Scorsese, who feels that "marvel movies aren't real cinema", this is a sign of disaster for the industry. However, no matter what opinion you take, blockbuster action movies drive ticket sales. 


