---
title: "CS_Working"
author: "Charlie Sturr"
date: "12/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(ggnewscale)
library(patchwork)
```

## Initial Analysis

```{r pressure, echo=TRUE}

movies <- read.csv("/Users/Charlie Sturr/OneDrive/Desktop/Columbia/01. Fall_2021/Data Viz/MOVIES_Final_12.11.2021_vAC.csv")

gross <- as.numeric(movies$Total.Gross)/100000
rating <- as.numeric(movies$average_rating)
audience_score <- as.numeric(movies$Score_Audience)
critic_score <- as.numeric(movies$Score_Rotten)

correlation_df <- data.frame(gross, rating, audience_score, critic_score)

#g1<- ggplot(correlation_df %>% filter(gross > 0), aes(x = rating, y = gross)) + geom_point()
#g2<- ggplot(correlation_df %>% filter(gross > 1000), aes(x = rating, y = gross)) + geom_point()
#g3<- ggplot(correlation_df %>% filter(gross > 2000), aes(x = rating, y = gross)) + geom_point()
#g4<- ggplot(correlation_df %>% filter(gross > 5000), aes(x = rating, y = gross)) + geom_point()



g1<- ggplot(correlation_df %>% filter(gross > 0), aes(x = audience_score, y = critic_score)) + geom_point()
g2<- ggplot(correlation_df %>% filter(gross > 1000), aes(x = audience_score, y = critic_score)) + geom_point()
g3<- ggplot(correlation_df %>% filter(gross > 2000), aes(x = audience_score, y = critic_score)) + geom_point()
g4<- ggplot(correlation_df %>% filter(gross > 5000), aes(x = audience_score, y = critic_score)) + geom_point()

g1 + g2 + g3 + g4 +plot_layout(widths = c(1, 1), heights = c(1,1))


#test 

```


##Box and Whisker


```{r pressure, echo=TRUE}

movies <- read.csv("/Users/Charlie Sturr/OneDrive/Desktop/Columbia/01. Fall_2021/Data Viz/MOVIES_Final_12.11.2021_vAC.csv")

correlation_df$band <- 1
  
  
  
correlation_df <- correlation_df %>%
                  mutate(band = ifelse(rating <1, "0-0.9", 
                                ifelse(rating<2, "1-1.9",
                                      ifelse(rating<3,"2-2.9",
                                             ifelse(rating<4,"3-3.9",
                                                    ifelse(rating<5,"4-4.9",
                                                           ifelse(rating<6,"5-5.9",
                                                                  ifelse(rating<7,"6-6.9",
                                                                         ifelse(rating<8,"7-7.9",
                                                                                ifelse(rating<9,"8-8.9",
                                                                                       ifelse(rating<=10,"9-10")))))))))))



ggplot(data = correlation_df, mapping = aes(x = gross, y = band)) + 
  geom_boxplot(outlier.color = 'red') + xlab("gross") + ylab("ratings band") + ggtitle("Box Plot of gross by ratings band")+   theme(plot.title = element_text(hjust = 0.5))

```
