--- 
title: "Movie Rating Analysis Test"
author: "Sharmi Mathur, Charlie Sturr, Ayush Baral"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

In the world of rotten tomatoes, metacritic, IMDB, and many others, movies are often picked apart
by critics before audiences have a chance to even see the film. Although audiences often turn to these
resources as a way to gauge their interest in seeing the actual film, many executives have bemoaned
the prevalence of online reviews. A 2017 New York Times article, which explores Hollywood’s reaction
to a flat 2017 summer season, quotes industry insiders as saying: ”I think it’s [Rotten Tomatoes] the
destruction of our business” (Brett Ratner, director, producer and film financier).

For our final project, we decided to take a deeper look at the entertainment industry. Therefore, our
questions and objectives for this project will be centered around exploring the relationship audience / critic perception and box office performance, to see if Hollywood executives
have taken any basic statistics courses and are justified in their complaints about the negative impact
of Rotten Tomatoes (and others).

### Our questions are as follows:
1. How have Rotten Tomatoes / IMDB Ratings trended over time? Are audiences
getting more or less pessimistic?
2. How have box office returns trended over time? Are movies making more money or less? How
are box office returns distributed? Is there a more equitable split across all movies released in a
given quarter or have earnings consolidated?
3. What is the correlation between audience scores and box office success?
4. What was the impact of COVID on box office returns? What about on Audience / Critic perception? 
5. How does movie genre impact these previous questions? Can we split across horror / action /
romance / etc.?
